language: python

sudo: false

cache: pip

addons:
  apt:
    packages:
      - ldap-utils
      - slapd
      - enchant
  coverity_scan:
    project:
      name: "tiran/python-ldap"
      description: "python-ldap"
    notification_email: christian@python.org
    # build_command_prepend: "<Your build preprocessing command here>"
    build_command: python3 setup.py build
    branch_pattern: coverity_scan


# Note: when updating Python versions, also change setup.py and tox.ini
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27
        - WITH_GCOV=1
    - python: 3.4
      env:
        - TOXENV=py34
        - WITH_GCOV=1
    - python: 3.5
      env:
        - TOXENV=py35
        - WITH_GCOV=1
    - python: 3.6
      env:
        - TOXENV=py36
        - WITH_GCOV=1
    - python: pypy
      env:
        - TOXENV=pypy
    - python: 3.7
      env:
        - TOXENV=py37
        - WITH_GCOV=1
      dist: xenial
      sudo: true
    - python: 3.8
      env:
        - TOXENV=py38
        - CFLAGS_std="-std=c99"
        - WITH_GCOV=1
      dist: xenial
      sudo: true
    - python: 3.9-dev
      env:
        - TOXENV=py39
        - CFLAGS_std="-std=c99"
        - WITH_GCOV=1
      dist: xenial
      sudo: true
    - python: 2.7
      env:
        - TOXENV=py2-nosasltls
        - WITH_GCOV=1
    - python: 3.6
      env:
        - TOXENV=py3-nosasltls
        - WITH_GCOV=1
    - python: 3.6
      env:
        - TOXENV=py3-trace
    - python: 3.6
      env: TOXENV=doc
  allow_failures:
     - env:
        - TOXENV=pypy

env:
    global:
        # -Wno-int-in-bool-context: don't complain about PyMem_MALLOC()
        # -Werror: turn all warnings into fatal errors
        # -Werror=declaration-after-statement: strict ISO C90
        - CFLAGS_warnings="-Wno-int-in-bool-context -Werror -Werror=declaration-after-statement"
        # Keep C90 compatibility where possible.
        # (Python 3.8+ headers use C99 features, so this needs to be overridable.)
        - CFLAGS_std="-std=c90"
        # pass CFLAGS, CI (for Travis CI) and WITH_GCOV to tox tasks
        - TOX_TESTENV_PASSENV="CFLAGS CI WITH_GCOV"
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        # via the "travis encrypt" command using the project repo's public key
        - secure: "EYkuvVfoa0/kybpC2AsQtM6oS7WgYUV1Lfkcu60M/gg67YuCrdq0spefJFKqbuNvEWCOTYCpCMzCx7FpS7Kefsqjyl3E/kExBav5/iT2eQ+JJ+ZxoIPpmCQlywWAVlcrh92s7nK15S7Hy565O8g3bw3Qh5N+KhhR2A2D7lfIxxau7RLQ4qixDkeDhsUmMjvJHyQZDNSFfSnryX9uA8k7JbDpnGVcNFsWVQntTwF8weyB5UHDfGDW4llghn7eLMS0pKkk4Q1wopsrkatrNpz+lTopL7f9jY8nC3fnI2JXN/D7FTDIcQ/m8yPtLgysJSKCTw2uzUUJMwUnUtWo36jTM4G+oW1wAkl3X9YDIgeVJw9XkP1gMfbi7SQRcJTjGuV/ri0fv4BtPkE3DTtx7ZdDxsV3o2gblaA/WYv7ypCNFd+P81+hxXdI0oxa3cE2hqZM9fvuK3QR1ga+OwpViyMEqnVlQtSzLL796tdmliMjg6Czf0D28Z1RTVdr2YTf3ozSzN9eVQYg/1Y2kEMonhz0TAOgHjSHjyWnzYIZ8stUK530FPNBTb61N9MD1jFQu4sOj7XfBvOwAyWHh9u8fU0Qqf0CrZFE+L8xoabq+MA6ySF77pYs5d/zs9gDElqcyTSY3YQLVKuuX2IHJohsFR6m0onrtgViKhHvAEjz0oAPtf4="


install:
  - pip install "pip>=7.1.0"
  - pip install tox-travis tox codecov
  # Coverage 5.0+ has issues similar to:
  #   https://github.com/nedbat/coveragepy/issues/915
  - pip install "coverage<5.0"

script: CFLAGS="$CFLAGS_warnings $CFLAGS_std" tox

after_success:
  # gather Python coverage
  - python -m coverage combine
  # send Python and GCOV coverage
  - codecov
